Добавляет ДЗ 9.13-валидация полей формы
htmlacademy-javascript/2390201-kekstagram-33 pull request #9
Opened 2024-11-21 00:55 UTC by romnosk

2024-11-22 14:23 UTC, Kartaviy-arteom commented on js/util.js
> +  keksogramBody.classList.add('modal-open');
document.body

2024-11-22 14:25 UTC, Kartaviy-arteom commented on js/upload-images.js
> +const hashtagErrorMessage = '1. Хэштег начинается с символа # (решётка);<br>2. Строка после решётки должна состоять из букв и чисел и не может содержать пробелы, спецсимволы (#, @, $ и т. п.), символ
не нужно выводить сразу все ошибки, если они все не произошли

2024-11-22 14:27 UTC, Kartaviy-arteom commented on js/upload-images.js
> +const maxHashtagsLength = 20;
критерии именований

2024-11-23 00:55 UTC, romnosk commented on js/util.js
> +  keksogramBody.classList.add('modal-open');
Исправил.

2024-11-23 00:55 UTC, romnosk commented on js/upload-images.js
> +const maxHashtagsLength = 20;
Исправил.

2024-11-24 01:23 UTC, romnosk commented on js/upload-images.js
> +const hashtagErrorMessage = '1. Хэштег начинается с символа # (решётка);<br>2. Строка после решётки должна состоять из букв и чисел и не может содержать пробелы, спецсимволы (#, @, $ и т. п.), символ
Исправил

2024-11-25 13:49 UTC, Kartaviy-arteom commented on js/upload-images.js
> +const IMG_SCALE_DEFAULT = 100;
константы должны находиться в начале

2024-11-25 13:50 UTC, Kartaviy-arteom commented on js/upload-images.js
> +        hashtagErrorMessage = 'Один и тот же хэштег не может быть использован дважды, при этом хэштеги нечувствительны к регистру: #ХэшТег и #хэштег считаются одним и тем же тегом';
строки нужно вынести в константы

2024-11-25 13:50 UTC, Kartaviy-arteom commented on js/upload-images.js
> +  if (scaleValue > 0 && scaleValue < 100) {
значения тоже в константы

2024-11-25 13:51 UTC, Kartaviy-arteom commented on js/upload-images.js
> +// Модуль загрузки изображений, отвечает за работу с формой загрузки (задание 9.1)
этот модуль лучше разделить

2024-11-25 14:23 UTC, Kartaviy-arteom commented on js/upload-images.js
> +    if (hashtag !== '') {
if (!hashtag) {

2024-11-25 22:20 UTC, romnosk commented on js/upload-images.js
> +    if (hashtag !== '') {
Я прбовал, но return не прерывает foreach((

2024-11-25 22:21 UTC, romnosk commented on js/upload-images.js
> +        hashtagErrorMessage = 'Один и тот же хэштег не может быть использован дважды, при этом хэштеги нечувствительны к регистру: #ХэшТег и #хэштег считаются одним и тем же тегом';
Исправил

2024-11-25 22:23 UTC, romnosk commented on js/upload-images.js
> +  if (scaleValue > 0 && scaleValue < 100) {
Исправил

2024-11-28 02:56 UTC, romnosk commented on js/upload-images.js
> +// Модуль загрузки изображений, отвечает за работу с формой загрузки (задание 9.1)
Решил разделить после того, как "начерно" реализую всю требуемую функциональность, в рамках рефакторинга.

2024-11-28 02:57 UTC, romnosk commented on js/upload-images.js
> +// Модуль загрузки изображений, отвечает за работу с формой загрузки (задание 9.1)
Сейчас даже не соображу, как к этому модулю подойти с разбиением(

2024-11-29 12:03 UTC, Kartaviy-arteom requested changes

2024-11-29 12:03 UTC, Kartaviy-arteom commented on js/api.js
> +  'https://32.javascript.htmlacademy.pro/kekstagram/data')
это константы

2024-11-29 12:03 UTC, Kartaviy-arteom commented on js/api.js
> +  'https://32.javascript.htmlacademy.pro/kekstagram',
методы тоже вынести в константы

2024-11-29 12:03 UTC, Kartaviy-arteom commented on js/upload-images.js
> +const MAX_HASHTAGS_NUMBER = 5;
константы перед основным кодом по всем модулям

2024-11-29 12:03 UTC, Kartaviy-arteom commented on js/upload-images.js
> +    if (hashtag !== '') {
он его и не должен прервать, он пропустит выполнения ряда действий для невалидного тега

2024-11-29 12:03 UTC, Kartaviy-arteom commented on js/upload-images.js
> +        hashtagErrorMessage = MessagesHashtagError.SHORT_HASHTAG;
этой можно все одной регуляркой проверить

2024-11-29 12:03 UTC, Kartaviy-arteom commented on js/user-messages.js
> +  if (evt.key === 'Escape') {
в константы

2024-12-02 00:08 UTC, romnosk commented on js/api.js
> +  'https://32.javascript.htmlacademy.pro/kekstagram/data')
Исправил.

2024-12-02 00:08 UTC, romnosk commented on js/api.js
> +  'https://32.javascript.htmlacademy.pro/kekstagram',
Исправил.

2024-12-02 00:19 UTC, romnosk commented on js/user-messages.js
> +  if (evt.key === 'Escape') {
Исправил.

2024-12-03 17:50 UTC, merged